# Generated by Django 4.2.3 on 2023-07-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_color_person_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_Shades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_shades', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='shades',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.color_shades'),
        ),
    ]
